**Z_Test**

In [15]:
import scipy.stats as st
import numpy as np


In [16]:
sam_mean = 90
pop_mean = 82
std =20
n = 81
alpha = 0.05

In [17]:
z_cal = (sam_mean - pop_mean)/(std/(np.sqrt(n)))
z_cal

3.5999999999999996

In [30]:
z_table = st.norm.ppf(1-alpha)
z_table

1.6448536269514722

In [31]:
if z_cal > z_table:
    print('Reject H0')
else:
    print('Accept H0')

Reject H0


**T_Test**

In [37]:
sam_mean = 248
pop_mean = 250
s_std =25
num = 5
alpha = 0.025

In [38]:
t_cal = (sam_mean - pop_mean)/(s_std/(np.sqrt(n)))
t_cal

-0.72

In [50]:
t_table = st.t.ppf(1-alpha, num-1)
t_table = -(t_table)
t_table

-2.7764451051977987

In [42]:
if t_table < t_cal:
    print('REJECT H0')
else:
    print('Accept H0')

REJECT H0


**Chi-Square Test**

**Problem # 1**

In [ ]:
n = 6

In [ ]:
df = n-1

In [54]:
ob = np.array([22, 17, 20, 26, 22, 13])
ex = np.array([20, 20, 20, 20, 20, 20])
ob , ex

(array([22, 17, 20, 26, 22, 13]), array([20, 20, 20, 20, 20, 20]))

In [55]:
np.sum((np.square(ob-ex))/ex)

5.1000000000000005

**Problem # 2**

In [58]:
Male =np.array([40, 45, 25, 10])
Female = np.array([35, 30, 20, 30])
Male , Female

(array([40, 45, 25, 10]), array([35, 30, 20, 30]))

In [59]:
N = np.sum(Male) + np.sum(Female)
N

235

In [62]:
sum_male = np.sum(Male)
sum_female = np.sum(Female)
rows_sum = np.array([sum_male , sum_female])

In [63]:
rows_sum

array([120, 115])

In [61]:
sum_col = Male + Female
sum_col

array([75, 75, 45, 40])

In [66]:
exp = []
for i in rows_sum:
  for j in sum_col:
    value = i*j/N
    exp.append(value)

In [67]:
exp

[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [70]:
obj = np.array([40, 45, 25, 10, 35, 30, 20, 30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [72]:
chi_square = np.sum(np.square(obj-exp)/exp)

In [73]:
chi_square

13.788747987117553